export const APP_CONFIG = Object.freeze({
  appName: "ORBIT",
  appExpansion: "Open Roadmap for Building Intuition and Theory",
  activeRoute: "Electromagnetismo",
  activeCourseId: "electromagnetism-applied",
  version: "0.4.3",
  locale: "es-CL",
  storagePrefix: "orbit-progress",
  legacyStoragePrefixes: Object.freeze(["aea-progress"]),
  progressSchemaVersion: 4,
  legacyCourseRevision: "electromagnetism-applied:legacy",
  defaultProfile: "student",
  teacherProfile: "teacher",
  debugProfile: "debug",
  baseMoveSpeed: 235,
  playerRadius: 14,
  cameraFollowRate: 7.5,
  minZoom: 0.28,
  maxZoom: 1.55,
  defaultZoom: 0.88,
  positionSaveIntervalMs: 900,
  interactionRadius: 72,
});

export const DEBUG_DEFAULTS = Object.freeze({
  enabled: false,
  noclip: false,
  showIds: true,
  showGraph: false,
  showCoords: true,
});
